// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LayoutClient from "./LayoutClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Aqui podemos declarar o metadata, pois esse arquivo é um Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-hscreen bg-background font-sans antialiased",
          geistSans,
          geistMono
        )}
      >
        {/*
          Renderizamos o componente cliente (LayoutClient) abaixo,
          para poder usar 'usePathname()' e mostrar/ocultar a Sidebar
        */}
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
