// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { AuthProvider } from "./contexts/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Aqui podemos declarar o metadata, pois esse arquivo é um Server Component
export const metadata: Metadata = {
  title: "VSC Passeios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-hscreen bg-background font-sans antialiased",
          geistSans,
          geistMono
        )}
      >
        <AuthProvider>
          <Toaster duration={2500} richColors />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
